services:
  - type: web
    name: xlytics-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
        sync: false # set it manually from Render dashboard or keep false if using secrets
